<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.0 /home/enisdev/code/logoAnimation/static/models/logoCenter.glb --root /models/ --types --printwidth 120 --precision 2
-->

<script lang="ts">
	import * as THREE from 'three'
	import { Group } from 'three'
	import {
		T,
		type Props,
		type Events,
		type Slots,
		forwardEventHandlers,
	} from '@threlte/core'
	import { useGltf } from '@threlte/extras'
	import { base } from '$app/paths'
	import { tweened } from 'svelte/motion'
	import { backOut } from 'svelte/easing'

	type $$Props = Props<THREE.Group>
	type $$Events = Events<THREE.Group>
	type $$Slots = Slots<THREE.Group> & { fallback: {}; error: { error: any } }

	export const ref = new Group()

	type GLTFResult = {
		nodes: {
			logoMesh: THREE.Mesh
		}
		materials: {
			['SVGMat.003']: THREE.MeshStandardMaterial
		}
	}

	const gltf = useGltf<GLTFResult>(base + '/models/logoCompressed.glb', {
		useDraco: true,
	})

	const component = forwardEventHandlers()

	const scale = tweened(0, { duration: 600, easing: backOut })
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
	{#await gltf}
		<slot name="fallback" />
	{:then gltf}
		<T.Mesh
			geometry={gltf.nodes.logoMesh.geometry}
			transition={scale.set(1)}
			scale={$scale}
			material={new THREE.MeshPhysicalMaterial({
				clearcoat: 0.5,
				clearcoatRoughness: 0.5,
				metalness: 0.5,
				roughness: 0.5,
				color: '#1a1c21',
			})}
			position={[0, 0, 0]}
			rotation={[Math.PI / 2, 0, 0]} />
	{:catch error}
		<slot name="error" {error} />
	{/await}

	<slot {ref} />
</T>
